Name: Release UI-TARS app
on:
  workflow_dispatch:

env:
  CI: true
  NODE_OPTIONS: --max-old-space-size=8192
  HUSKY: 0

permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  publish_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show operating system info
        run: |
          echo "Operating System:"
          cmd /c ver
      - name: Install pnpm
        run: npm install -g pnpm@9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: install dependencies
        run: pnpm install
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd apps/ui-tars && pnpm run publish:win32
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UI-TARS-Windows-Exe
          path: apps/ui-tars/out/*.exe
